sources:
  bundler: true
  npm: true

allowed:
  - 'mit'
  - 'apache-2.0'
  - 'cc0-1.0'
  - 'isc'
  - 'bsd-2-clause'
  - 'bsd-3-clause'

reviewed:
  bundler:
    - 'activerecord'
    - 'activerecord-nulldb-adapter'
    - 'ansi'
    - 'bcrypt'
    - 'concurrent-ruby'
    - 'elasticsearch'
    - 'elasticsearch-api'
    - 'elasticsearch-transport'
    - 'ffi'
    - 'method_source'
    - 'nokogiri'
    - 'omniauth'
    - 'pg'
    - 'pg_query'
    - 'puma'
    - 'rack'
    - 'swagger-blocks'
    - 'tilt'
    - 'rack-health'
    - 'newrelic_rpm'
    - 'awesome_print'
    - 'coderay'
    - 'json'
    - 'jwt'
    - 'logstash-event'
    - 'prometheus-client'
    - 'pry'
    - 'rack-health'

  npm:
    - '@webassemblyjs/helper-fsm'
    - '@webassemblyjs/leb128'
    - '@xtuc/ieee754'
    - '@vue/component-compiler-utils'
    - 'abbrev'
    - 'amdefine'
    - 'atob'
    - 'bcrypt-pbkdf'
    - 'block-stream'
    - 'browserify-zlib'
    - 'boolbase'
    - 'cacache'
    - 'caniuse-lite'
    - 'case-sensitive-paths-webpack-plugin'
    - 'chrome-trace-event'
    - 'color-convert'
    - 'concat-map'
    - 'core-js-compat'
    - 'dashdash'
    - 'de-indent'
    - 'defined'
    - 'detective'
    - 'dom-serializer'
    - 'domain-browser'
    - 'electron-to-chromium'
    - 'envify'
    - 'errno'
    - 'esprima-fb'
    - 'fast-json-stable-stringify'
    - 'figgy-pudding'
    - 'fs.realpath'
    - 'headful'
    - 'https-browserify'
    - 'ieee754'
    - 'imurmurhash'
    - 'is-typedarray'
    - 'jsbn'
    - 'json-schema'
    - 'json5'
    - 'jstransform'
    - 'lodash'
