AllCops:
  Exclude:
    - "bin/*"
    - "config/spring.rb"
    - "db/schema.rb"
    - "node_modules/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Layout/IndentFirstHashElement:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/SymbolArray:
  Enabled: false
