version: "3.7"

volumes:
  postresql_data: {}
  redis_data: {}
  elasticsearch_data: {}

services:
  postgresql:
    image: "postgres:12.1"
    container_name: "evemonk_postgresql"
    restart: "unless-stopped"
    volumes:
      - "postresql_data:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.2"
    container_name: "evemonk_elasticsearch"
    restart: "unless-stopped"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256M -Xmx256M"
    ports:
      - "9200:9200"

  redis:
    image: "redis:5.0.7"
    container_name: "evemonk_redis"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

  memcached:
    image: "memcached:1.5.21"
    container_name: "evemonk_memcached"
    restart: "unless-stopped"
    command: memcached -m 64
    ports:
      - "11211:11211"
