:queues:
  - mailers
  - default
  - server_status

:concurrency: 5

:schedule:
  pg_hero_query_stats:
    every: 5m
    class: Pghero::CaptureQueryStatsWorker
    description: 'Collect postgresql query stats'
  pg_hero_space_stats:
    every: 1d
    class: Pghero::CaptureSpaceStatsWorker
    description: 'Collection postgresql space stats'
  sitemap_updater:
    every: 1d
    class: SitemapUpdaterWorker
    description: 'Update sitemap and ping google'
  eve_server_status:
    every: 1m
    class: Eve::ServerStatusImporterWorker
    description: 'Server status'
  eve_races:
    every: 7d
    class: Eve::RacesImporterWorker
    description: 'Import Races'
  eve_races_translations:
    every: 7d
    class: Eve::RacesTranslationsImporterWorker
    description: 'Import Races translations'
  eve_bloodlines:
    every: 7d
    class: Eve::BloodlinesImporterWorker
    description: 'Import Bloodlines'
  eve_ancestries:
    every: 7d
    class: Eve::AncestriesImporterWorker
    description: 'Import Ancestries'
  eve_factions:
    every: 7d
    class: Eve::FactionsImporterWorker
    description: 'Import Factions'
  eve_alliances:
    every: 1d
    class: Eve::AlliancesImporterWorker
    description: 'Import Alliances index'
  eve_alliances_local:
    every: 1d
    class: Eve::LocalAlliancesImporterWorker
    description: 'Import Alliances info'
  eve_alliances_corporations:
    every: 1d
    class: Eve::AlliancesCorporationsImporterWorker
    description: 'Import Alliances Corporations info'
  eve_corporations:
    every: 1d
    class: Eve::CorporationsImporterWorker
    description: 'Import Corporations info'
  eve_characters:
    every: 7d
    class: Eve::CharactersImporterWorker
    description: 'Import Characters info'
  eve_graphics:
    every: 7d
    class: Eve::GraphicsImporterWorker
    description: 'Import Graphics index'
  eve_graphics_local:
    every: 7d
    class: Eve::LocalGraphicsImporterWorker
    description: 'Import Graphics info'
  eve_types:
    every: 7h
    class: Eve::TypesImporterWorker
    description: 'Import Types index'
  eve_types_local:
    every: 7d
    class: Eve::LocalTypesImporterWorker
    description: 'Import Types info'
#  eve_systems:
#    every: 1d
#    class: Eve::SystemsImporterWorker
