:queues:
  - [server_status, 2]
  - mailers
  - default

:concurrency: 10

:schedule:
  pg_hero_query_stats:
    every: 5m
    class: Pghero::CaptureQueryStatsWorker
    description: 'Collect postgresql query stats'
  pg_hero_space_stats:
    every: 1d
    class: Pghero::CaptureSpaceStatsWorker
    description: 'Collection postgresql space stats'
  eve_graphics_local:
    every: 7d
    class: Eve::LocalGraphicsImporterWorker
    description: 'Import Graphics info'
  eve_types:
    every: 1d
    class: Eve::TypesImporterWorker
    description: 'Import Types index'
#  eve_systems:
#    every: 1d
#    class: Eve::SystemsImporterWorker
