Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf

# TODO: check this
# Layout/ExtraSpacing

# TODO: later
# Layout/ClassStructure

Layout/MultilineAssignmentLayout:
  Enabled: true

Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/TimeZone:
  EnforcedStyle: strict
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true
  EnforcedStyle: assign_to_condition

Style/EmptyMethod:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/NumericLiterals:
  Enabled: true
  Strict: true

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
