# rubocop-rspec cops

RSpec/ScatteredSetup:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

# https://robots.thoughtbot.com/don-t-stub-the-system-under-test
# Enable later?
RSpec/SubjectStub:
  Enabled: false

# Enable later
RSpec/ExampleWording:
  Enabled: false

# Bug in rubocop-rspec cop
RSpec/FilePath:
  Enabled: true

RSpec/NestedGroups:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

# Maybe later
RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false
