name: consistency_fail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  consistency_fail:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: run consistency_fail
        run: bundle exec consistency_fail
