name: mdl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mdl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: run mdl
        run: bundle exec mdl README.md
