name: prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yarn-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: run prettier
        run: yarn prettier --check "*.{yml,yaml,js,md}" "app/**/*.{js,css,scss}" ".circleci/*.{yml,yaml}" ".github/*.{yml,yaml}" ".github/**/*.{yml,yaml}" "config/**/*.{yml,yaml,js}" "doc/**/*.{yml,yaml}"
